#version 450
layout(local_size_x = 256) in;

layout(set = 0, binding = 0) buffer OutBuffer { float C[]; };
layout(set = 0, binding = 1) buffer InBufferA { float A[]; };
layout(set = 0, binding = 2) buffer InBufferB { float B[]; };

layout(push_constant) uniform PushConstants {
    uint N;
};

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= N)
        return;

    C[i] = A[i] + B[i];
}
